<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Birthdays</strong> within the next {days} days' => '',
    'In {days} days' => '',
    'becomes {years} years old.' => '',
    'Back to modules' => 'Torna ai moduli',
    'Birthday Module Configuration' => 'Configurazioni Modulo Compleanno',
    'Save' => 'Salva',
    'The number of days future bithdays will be shown within.' => 'Quanti giorni prima del compleanno visualizzare la notifica',
    'Tomorrow' => 'Domani',
    'You may configure the number of days within the upcoming birthdays are shown.' => 'Puoi configurare il numero di giorni entro il quale mostrare i prossimi compleanni in arrivo.',
    'today' => 'oggi',
];
