<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The group id of the group that should be exluded.' => '',
    'The number of days future birthdays will be shown within.' => '',
    '<strong>Birthdays</strong> within the next {days} days' => '<strong>Дни рождения</strong> в ближайшие {days, number} {days, plural, =1{день} =2{дня} =3{дня} =4{дня} other{дней}}',
    'Back to modules' => 'Назад к модулям',
    'Birthday Module Configuration' => 'Настройки модуля <strong>Дни рождения</strong>',
    'In {days} days' => 'Через {days, number} {days, plural, =1{день} =2{дня} =3{дня} =4{дня} other{дней}}',
    'Save' => 'Сохранить',
    'Tomorrow' => 'завтра',
    'You may configure the number of days within the upcoming birthdays are shown.' => 'Вы можете настроить количество предстоящих дней рождения для отображения в блоке.',
    'becomes {years} years old.' => 'исполнится {years, number} {years, plural, one{год} few{года} many{лет} other{лет}}',
    'today' => 'сегодня',
];
