<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The group id of the group that should be exluded.' => '',
    'The number of days future birthdays will be shown within.' => '',
    '<strong>Birthdays</strong> within the next {days} days' => '<strong>Cumpleaños</strong> dentro de los siguientes {days} días',
    'Back to modules' => 'Regresar a los Módulos',
    'Birthday Module Configuration' => 'Configuración del módulo Cumpleaños',
    'In {days} days' => 'En {days} días',
    'Save' => 'Guardar',
    'Tomorrow' => 'Mañana',
    'You may configure the number of days within the upcoming birthdays are shown.' => 'Debes configurar el número de días para mostrar los cumpleaños.',
    'becomes {years} years old.' => 'cumplirá {years} años de edad.',
    'today' => 'hoy',
];
