<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The group id of the group that should be exluded.' => '',
    'The number of days future birthdays will be shown within.' => '',
    '<strong>Birthdays</strong> within the next {days} days' => '次の{days}の日以内に<strong>誕生日</ strong>',
    'Back to modules' => 'モジュールへ戻る',
    'Birthday Module Configuration' => '誕生日モジュールの設定',
    'In {days} days' => '{days}日以内',
    'Save' => '保存',
    'Tomorrow' => '明日',
    'You may configure the number of days within the upcoming birthdays are shown.' => '今後の誕生日の日数を設定することができます。',
    'becomes {years} years old.' => '{years}歳になるでしょう。',
    'today' => '今日',
];
