<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to modules' => 'Voltar aos módulos',
    'Birthday Module Configuration' => 'Configuração do Módulo de Aniversário',
    'Save' => 'Salvar',
    'The number of days future bithdays will be shown within.' => 'O número de dias para exibição dos próximos aniversários no calendário.',
    'Tomorrow' => 'Amanhã',
    'Upcoming' => 'Próximos',
    'You may configure the number of days within the upcoming birthdays are shown.' => 'Você pode configurar o número de dias antes dos próximos aniversários para que sejam mostrados no calendário.',
    'becomes' => 'tornar-se',
    'birthdays' => 'aniversários',
    'days' => 'dias',
    'in' => 'em',
    'today' => 'hoje',
    'years old.' => 'anos de idade.',
];
