<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'No birthday.' => 'Geen verjaardagen.',
    'Back to modules' => 'Terug naar modules',
    'Birthday Module Configuration' => 'Verjaardagen module configuratie',
    'Save' => 'Opslaan',
    'The number of days future bithdays will be shown within.' => 'Het aantal dagen waarin toekomstige verjaardagen getoond worden.',
    'Tomorrow' => 'Morgen',
    'Upcoming' => 'Aankomende',
    'You may configure the number of days within the upcoming birthdays are shown.' => 'U kunt het aantal dagen waarin toekomstige verjaardagen getoond worden instellen.',
    'becomes' => 'wordt',
    'birthdays' => 'verjaardagen',
    'days' => 'dagen',
    'in' => 'binnen',
    'today' => 'vandaag',
    'years old.' => 'jaar oud.',
];
