<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The group id of the group that should be exluded.' => '',
    'The number of days future birthdays will be shown within.' => '',
    '<strong>Birthdays</strong> within the next {days} days' => '<strong>Verjaardagen</strong> in de komende {days} dagen',
    'Back to modules' => 'Terug naar modules',
    'Birthday Module Configuration' => 'Verjaardagen module configuratie',
    'In {days} days' => 'Over {days} dagen',
    'Save' => 'Opslaan',
    'Tomorrow' => 'Morgen',
    'You may configure the number of days within the upcoming birthdays are shown.' => 'U kunt het aantal dagen waarin toekomstige verjaardagen getoond worden instellen.',
    'becomes {years} years old.' => 'wordt {years} jaar oud.',
    'today' => 'vandaag',
];
