<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'No birthday.' => 'Žádné narozeniny.',
    'Back to modules' => 'Zpět na přehled modulů',
    'Birthday Module Configuration' => 'Nastavení modulu Narozeniny',
    'Save' => 'Uložit',
    'The number of days future bithdays will be shown within.' => 'Počet dnů v budoucnosti, ve kterých se budou zobrazovat narozeniny.',
    'Tomorrow' => 'Zítra',
    'Upcoming' => 'Nadcházející',
    'You may configure the number of days within the upcoming birthdays are shown.' => 'Můžete nastavit počet dnů před narozeninami, kdy na ně bude upozorněno.',
    'becomes' => 'bude',
    'birthdays' => 'narozeniny',
    'days' => 'dnů',
    'in' => 'za',
    'today' => 'dnes',
    'years old.' => 'let.',
];
