<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to modules' => 'Zurück zu den Modulen',
    'Birthday Module Configuration' => 'Konfiguration Geburtstagsmodul',
    'Save' => 'Speichern',
    'The number of days future bithdays will be shown within.' => 'Anzahl an Tagen, an denen zukünftige Geburtstage bereits angezeigt werden.',
    'Tomorrow' => 'Morgen',
    'Upcoming' => 'Demnächst',
    'You may configure the number of days within the upcoming birthdays are shown.' => 'Du kannst die Anzahl an Tagen einstellen, an denen zukünftige Geburstage bereits angezeigt werden.',
    'becomes' => 'wird',
    'birthdays' => 'Geburtstage',
    'days' => 'Tage',
    'in' => 'in',
    'today' => 'heute',
    'years old.' => 'Jahre alt.',
];
