<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Birthdays</strong> within the next {days} days' => '',
    'Back to modules' => '',
    'In {days} days' => '',
    'The group id of the group that should be exluded.' => '',
    'The number of days future birthdays will be shown within.' => '',
    'becomes {years} years old.' => '',
    'Birthday Module Configuration' => '生日模組設定',
    'Save' => '儲存',
    'Tomorrow' => '明天',
    'You may configure the number of days within the upcoming birthdays are shown.' => '您可設定多少天前會通知即將到來的生日',
    'today' => '今天',
];
