<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to modules' => '',
    'Birthday Module Configuration' => '生日模組設定',
    'Save' => '儲存',
    'The number of days future bithdays will be shown within.' => '多少天前會通知生日',
    'Tomorrow' => '明天',
    'Upcoming' => '即將到來',
    'You may configure the number of days within the upcoming birthdays are shown.' => '您可設定多少天前會通知即將到來的生日',
    'becomes' => '成為',
    'birthdays' => '生日',
    'days' => '天',
    'in' => '即將在',
    'today' => '今天',
    'years old.' => '歲',
];
