<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Birthday Module Configuration' => '',
    'The group id of the group that should be exluded.' => '',
    'The number of days future birthdays will be shown within.' => '',
    'You may configure the number of days within the upcoming birthdays are shown.' => '',
    '<strong>Birthdays</strong> within the next {days} days' => '<strong>Születésnap </strong>a következő {days} napban',
    'Back to modules' => 'Vissza a modulokhoz',
    'In {days} days' => '{days} múlva',
    'Save' => 'Mentés',
    'Tomorrow' => 'Holnap',
    'becomes {years} years old.' => '{years} éves lesz.',
    'today' => 'ma',
];
